//13) Solicite dois nomes e apresente qual nome é maior (
//segundo a ordem alfabética))

algoritmo "semnome"

var

nome1,nome2:caracter

inicio

Escreval("Digite o primeiro nome:")
leia(nome1)

Escreval("Digite o segundo nome:")
leia(nome2)

se (nome1 > nome2) entao

Escreval("O nome maior em ordem alfabetica e: ", nome1)

senao

Escreval("O nome maior em ordem alfabetica e: ", nome2)

fimse



fimalgoritmo
